/* auto-generated by NAPI-RS */
/* eslint-disable */

export const enum AccessMode {
  Read = 0,
  Write = 1,
  ReadWrite = 2
}

export interface FsCapabilityInfo {
  original: string
  resolved: string
  access: string
  isFile: boolean
  source: string
}

export interface SupportInfoResult {
  isSupported: boolean
  platform: string
  details: string
}

export interface QueryResultInfo {
  status: string
  reason: string
  grantedPath?: string
  access?: string
  granted?: string
  requested?: string
}

export class CapabilitySet {
  constructor()
  /** Add directory access for the given path. */
  allowPath(path: string, mode: AccessMode): void
  /** Add single-file access for the given path. */
  allowFile(path: string, mode: AccessMode): void
  /** Block all outbound network access. */
  blockNetwork(): void
  /** Add a command to the allow list (overrides blocklists). */
  allowCommand(cmd: string): void
  /** Add a command to the block list. */
  blockCommand(cmd: string): void
  /** Add a raw platform-specific sandbox rule. */
  platformRule(rule: string): void
  /** Remove duplicate filesystem capabilities. */
  deduplicate(): void
  /** Check if the given path is covered by an existing directory capability. */
  pathCovered(path: string): boolean
  /** Get a list of all filesystem capabilities. */
  fsCapabilities(): FsCapabilityInfo[]
  /** Whether outbound network access is blocked. */
  get isNetworkBlocked(): boolean
  /** Get a plain-text summary of the capability set. */
  summary(): string
}

export class SandboxState {
  /** Create a SandboxState snapshot from a CapabilitySet. */
  static fromCaps(caps: CapabilitySet): SandboxState
  /** Serialize the state to a JSON string. */
  toJson(): string
  /** Deserialize state from a JSON string. */
  static fromJson(json: string): SandboxState
  /** Reconstruct a CapabilitySet from this state. */
  toCaps(): CapabilitySet
  /** Whether network is blocked in this state. */
  get netBlocked(): boolean
}

export class QueryContext {
  constructor(caps: CapabilitySet)
  /** Query whether a path operation is permitted. */
  queryPath(path: string, mode: AccessMode): QueryResultInfo
  /** Query whether network access is permitted. */
  queryNetwork(): QueryResultInfo
}

/**
 * Apply the sandbox with the given capabilities.
 * This is irreversible. Once applied, the current process and all children
 * can only access resources granted by the capabilities.
 */
export function apply(caps: CapabilitySet): void

/** Check if sandboxing is supported on this platform. */
export function isSupported(): boolean

/** Get detailed information about sandbox support on this platform. */
export function supportInfo(): SupportInfoResult
